### PR TITLE
Support for TeX/LaTeX grammar

### LINKED ISSUE #11: add grammar for php
see [contributing instructions](https://github.com/asottile/babi-grammars#internalcontributing-instructions) if you'd like to work on this

### PR DESCRIPTION
**Pull request by int3l**
This is needed in order to stop `babi` from crashing when trying to type the `text` keyword for markdown code blocks.
You already included the `perl` grammar ( which fixed the first crash for asottile/babi#121 )
Unfortunately, it also needs the TeX/LaTeX one.

(I think that you meant perl instead php, since you redirected me to the same issue, when I was having crashes with the `text` keyword)

### CODE REVIEW

**Comment by int3l** [comment]
Ammm, I don't what is going on with the CI:
```text
error: can't copy 'share/babi/grammar_v1\scope.terraform.json': doesn't exist or not a regular file
```
Never touched that file 🤷 :D

**Comment by asottile** [comment]
lol I think you windows-line-endings'd everything

**Comment by int3l** [comment]
yeah, can't find the setting for that -- anyways, I will have to setup this on linux I guess.

**Comment by int3l** [comment]
How you make the demos for those new grammars?
I saw the crystal/perl support commit and there was no additional files -- should I just exclude TeX as well at this point?

**Comment by asottile** [comment]
should just be a small example file in testdata (your current one is way too complicated, I would just use a very simple one) -- sometimes you need to use different file extensions to match `fileTypes` to render the other language

**Comment by int3l** [comment]
Not sure if this is enough -- can't find simple enough TeX style (`sty`) files or any of the other `bbx`, `cbx`.

**Comment by int3l** [comment]
Hmm, on further inspection it seems that this particular grammar is kind-a old and it doesn't properly highlight LaTeX/TeX content. Closing this one for now until I find something better -- maybe [James-Yu/LaTeX-Workshop](https://github.com/James-Yu/LaTeX-Workshop) or [jlelong/vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics)
But I am not sure for now.

**Pull request closed without merging**
