### PR TITLE
Added syntax highlighting of meson.build files

### PR DESCRIPTION
**Pull request by JustScreaMy**

### CODE REVIEW

**Review by asottile — APPROVED** [review]

**Comment by asottile** [comment]
looks like you'll need to add `identify` support for `meson.build` files

**Comment by JustScreaMy** [comment]
can you try to rerun the tests, after the support in `identify` has been added?

**Comment by asottile** [comment]
you can re-trigger tests by closing and reopening or by trivial-amend force pushing

**Pull request merged**
